# Generated by Django 2.0.2 on 2018-04-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selite', models.CharField(blank=True, max_length=250)),
                ('palautusaika', models.DateTimeField(auto_now_add=True)),
                ('korvausdokumentti', models.FileField(upload_to='korvaukset/')),
                ('korvaussumma', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('palauttaja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
