# Generated by Django 2.0.2 on 2018-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palautus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palauttaja', models.CharField(max_length=200)),
                ('palautuspvm', models.DateTimeField(verbose_name='korvauksen pvm')),
            ],
        ),
    ]
