# Generated by Django 2.0.2 on 2018-03-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='palauttaja',
        ),
    ]
