# Generated by Django 2.0.2 on 2018-03-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selite', models.CharField(blank=True, max_length=250)),
                ('palautusaika', models.DateTimeField(auto_now_add=True)),
                ('korvausdokumentti', models.FileField(upload_to='korvaukset/')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Palautus',
        ),
    ]
