# Generated by Django 2.0.2 on 2018-04-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
