# Generated by Django 2.0.2 on 2018-03-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180320_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='palauttaja',
        ),
    ]
