# Generated by Django 2.0.2 on 2018-04-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('LAH', 'LÄHETETTY'), ('HYV', 'HYVÄKSYTTY'), ('HYL', 'HYLÄTTY')], default='LAH', max_length=3),
        ),
    ]
