# Generated by Django 2.0.2 on 2018-03-21 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_document_palauttaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='palauttaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
